//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCClassSchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSearch
    {
        public string ClassID { get; set; }
        public string SearchGroup1 { get; set; }
        public string SearchGroup2 { get; set; }
        public string SearchGroup3 { get; set; }
        public string SearchGroup4 { get; set; }
        public string ItemYrqLink { get; set; }
    }
}
