IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CAMPUS\SSOUTHDT-N216K$')
CREATE LOGIN [CAMPUS\SSOUTHDT-N216K$] FROM WINDOWS
GO
CREATE USER [CAMPUS\SSOUTHDT-N216K$] FOR LOGIN [CAMPUS\SSOUTHDT-N216K$]
GO
