//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ClassSchedule.Models", "FK_Departments_Division", "Division", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CTCClassSchedule.Models.Division), "Department", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CTCClassSchedule.Models.Department), true)]
[assembly: EdmRelationshipAttribute("ClassSchedule.Models", "FK_Subjects_Departments", "Department", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CTCClassSchedule.Models.Department), "Subject", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CTCClassSchedule.Models.Subject), true)]
[assembly: EdmRelationshipAttribute("ClassSchedule.Models", "FK_SubjectsCoursePrefixes_Subjects", "Subject", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CTCClassSchedule.Models.Subject), "SubjectsCoursePrefix", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CTCClassSchedule.Models.SubjectsCoursePrefix), true)]

#endregion

namespace CTCClassSchedule.Models
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClassScheduleDb : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new ClassScheduleDb object using the connection string found in the 'ClassScheduleDb' section of the application configuration file.
        /// </summary>
        public ClassScheduleDb() : base("name=ClassScheduleDb", "ClassScheduleDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ClassScheduleDb object.
        /// </summary>
        public ClassScheduleDb(string connectionString) : base(connectionString, "ClassScheduleDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ClassScheduleDb object.
        /// </summary>
        public ClassScheduleDb(EntityConnection connection) : base(connection, "ClassScheduleDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassSearch> ClassSearches
        {
            get
            {
                if ((_ClassSearches == null))
                {
                    _ClassSearches = base.CreateObjectSet<ClassSearch>("ClassSearches");
                }
                return _ClassSearches;
            }
        }
        private ObjectSet<ClassSearch> _ClassSearches;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseSearch> CourseSearches
        {
            get
            {
                if ((_CourseSearches == null))
                {
                    _CourseSearches = base.CreateObjectSet<CourseSearch>("CourseSearches");
                }
                return _CourseSearches;
            }
        }
        private ObjectSet<CourseSearch> _CourseSearches;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Division> Divisions
        {
            get
            {
                if ((_Divisions == null))
                {
                    _Divisions = base.CreateObjectSet<Division>("Divisions");
                }
                return _Divisions;
            }
        }
        private ObjectSet<Division> _Divisions;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseMeta> CourseMetas
        {
            get
            {
                if ((_CourseMetas == null))
                {
                    _CourseMetas = base.CreateObjectSet<CourseMeta>("CourseMetas");
                }
                return _CourseMetas;
            }
        }
        private ObjectSet<CourseMeta> _CourseMetas;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SectionCourseCrosslisting> SectionCourseCrosslistings
        {
            get
            {
                if ((_SectionCourseCrosslistings == null))
                {
                    _SectionCourseCrosslistings = base.CreateObjectSet<SectionCourseCrosslisting>("SectionCourseCrosslistings");
                }
                return _SectionCourseCrosslistings;
            }
        }
        private ObjectSet<SectionCourseCrosslisting> _SectionCourseCrosslistings;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SectionsMeta> SectionsMetas
        {
            get
            {
                if ((_SectionsMetas == null))
                {
                    _SectionsMetas = base.CreateObjectSet<SectionsMeta>("SectionsMetas");
                }
                return _SectionsMetas;
            }
        }
        private ObjectSet<SectionsMeta> _SectionsMetas;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubjectsCoursePrefix> SubjectsCoursePrefixes
        {
            get
            {
                if ((_SubjectsCoursePrefixes == null))
                {
                    _SubjectsCoursePrefixes = base.CreateObjectSet<SubjectsCoursePrefix>("SubjectsCoursePrefixes");
                }
                return _SubjectsCoursePrefixes;
            }
        }
        private ObjectSet<SubjectsCoursePrefix> _SubjectsCoursePrefixes;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SectionSeat> SectionSeats
        {
            get
            {
                if ((_SectionSeats == null))
                {
                    _SectionSeats = base.CreateObjectSet<SectionSeat>("SectionSeats");
                }
                return _SectionSeats;
            }
        }
        private ObjectSet<SectionSeat> _SectionSeats;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_Class> vw_Class
        {
            get
            {
                if ((_vw_Class == null))
                {
                    _vw_Class = base.CreateObjectSet<vw_Class>("vw_Class");
                }
                return _vw_Class;
            }
        }
        private ObjectSet<vw_Class> _vw_Class;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subject> Subjects
        {
            get
            {
                if ((_Subjects == null))
                {
                    _Subjects = base.CreateObjectSet<Subject>("Subjects");
                }
                return _Subjects;
            }
        }
        private ObjectSet<Subject> _Subjects;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the ClassSearches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassSearches(ClassSearch classSearch)
        {
            base.AddObject("ClassSearches", classSearch);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the CourseSearches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseSearches(CourseSearch courseSearch)
        {
            base.AddObject("CourseSearches", courseSearch);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Divisions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDivisions(Division division)
        {
            base.AddObject("Divisions", division);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the CourseMetas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseMetas(CourseMeta courseMeta)
        {
            base.AddObject("CourseMetas", courseMeta);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the SectionCourseCrosslistings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSectionCourseCrosslistings(SectionCourseCrosslisting sectionCourseCrosslisting)
        {
            base.AddObject("SectionCourseCrosslistings", sectionCourseCrosslisting);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the SectionsMetas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSectionsMetas(SectionsMeta sectionsMeta)
        {
            base.AddObject("SectionsMetas", sectionsMeta);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the SubjectsCoursePrefixes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubjectsCoursePrefixes(SubjectsCoursePrefix subjectsCoursePrefix)
        {
            base.AddObject("SubjectsCoursePrefixes", subjectsCoursePrefix);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the SectionSeats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSectionSeats(SectionSeat sectionSeat)
        {
            base.AddObject("SectionSeats", sectionSeat);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_Class EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_Class(vw_Class vw_Class)
        {
            base.AddObject("vw_Class", vw_Class);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Subjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubjects(Subject subject)
        {
            base.AddObject("Subjects", subject);
        }

        #endregion
    }


    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="ClassSearch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassSearch : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new ClassSearch object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static ClassSearch CreateClassSearch(global::System.String classID)
        {
            ClassSearch classSearch = new ClassSearch();
            classSearch.ClassID = classID;
            return classSearch;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SearchGroup1
        {
            get
            {
                return _SearchGroup1;
            }
            set
            {
                OnSearchGroup1Changing(value);
                ReportPropertyChanging("SearchGroup1");
                _SearchGroup1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SearchGroup1");
                OnSearchGroup1Changed();
            }
        }
        private global::System.String _SearchGroup1;
        partial void OnSearchGroup1Changing(global::System.String value);
        partial void OnSearchGroup1Changed();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SearchGroup2
        {
            get
            {
                return _SearchGroup2;
            }
            set
            {
                OnSearchGroup2Changing(value);
                ReportPropertyChanging("SearchGroup2");
                _SearchGroup2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SearchGroup2");
                OnSearchGroup2Changed();
            }
        }
        private global::System.String _SearchGroup2;
        partial void OnSearchGroup2Changing(global::System.String value);
        partial void OnSearchGroup2Changed();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SearchGroup3
        {
            get
            {
                return _SearchGroup3;
            }
            set
            {
                OnSearchGroup3Changing(value);
                ReportPropertyChanging("SearchGroup3");
                _SearchGroup3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SearchGroup3");
                OnSearchGroup3Changed();
            }
        }
        private global::System.String _SearchGroup3;
        partial void OnSearchGroup3Changing(global::System.String value);
        partial void OnSearchGroup3Changed();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SearchGroup4
        {
            get
            {
                return _SearchGroup4;
            }
            set
            {
                OnSearchGroup4Changing(value);
                ReportPropertyChanging("SearchGroup4");
                _SearchGroup4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SearchGroup4");
                OnSearchGroup4Changed();
            }
        }
        private global::System.String _SearchGroup4;
        partial void OnSearchGroup4Changing(global::System.String value);
        partial void OnSearchGroup4Changed();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemYrqLink
        {
            get
            {
                return _ItemYrqLink;
            }
            set
            {
                OnItemYrqLinkChanging(value);
                ReportPropertyChanging("ItemYrqLink");
                _ItemYrqLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemYrqLink");
                OnItemYrqLinkChanged();
            }
        }
        private global::System.String _ItemYrqLink;
        partial void OnItemYrqLinkChanging(global::System.String value);
        partial void OnItemYrqLinkChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="CourseMeta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseMeta : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new CourseMeta object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        public static CourseMeta CreateCourseMeta(global::System.String courseID)
        {
            CourseMeta courseMeta = new CourseMeta();
            courseMeta.CourseID = courseID;
            return courseMeta;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Footnote
        {
            get
            {
                return _Footnote;
            }
            set
            {
                OnFootnoteChanging(value);
                ReportPropertyChanging("Footnote");
                _Footnote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Footnote");
                OnFootnoteChanged();
            }
        }
        private global::System.String _Footnote;
        partial void OnFootnoteChanging(global::System.String value);
        partial void OnFootnoteChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="CourseSearch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseSearch : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new CourseSearch object.
        /// </summary>
        /// <param name="courseKey">Initial value of the CourseKey property.</param>
        /// <param name="yearQuarterID">Initial value of the YearQuarterID property.</param>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        public static CourseSearch CreateCourseSearch(global::System.String courseKey, global::System.String yearQuarterID, global::System.String courseID)
        {
            CourseSearch courseSearch = new CourseSearch();
            courseSearch.CourseKey = courseKey;
            courseSearch.YearQuarterID = yearQuarterID;
            courseSearch.CourseID = courseID;
            return courseSearch;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseKey
        {
            get
            {
                return _CourseKey;
            }
            set
            {
                if (_CourseKey != value)
                {
                    OnCourseKeyChanging(value);
                    ReportPropertyChanging("CourseKey");
                    _CourseKey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseKey");
                    OnCourseKeyChanged();
                }
            }
        }
        private global::System.String _CourseKey;
        partial void OnCourseKeyChanging(global::System.String value);
        partial void OnCourseKeyChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String YearQuarterID
        {
            get
            {
                return _YearQuarterID;
            }
            set
            {
                OnYearQuarterIDChanging(value);
                ReportPropertyChanging("YearQuarterID");
                _YearQuarterID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("YearQuarterID");
                OnYearQuarterIDChanged();
            }
        }
        private global::System.String _YearQuarterID;
        partial void OnYearQuarterIDChanging(global::System.String value);
        partial void OnYearQuarterIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseInfo
        {
            get
            {
                return _CourseInfo;
            }
            set
            {
                OnCourseInfoChanging(value);
                ReportPropertyChanging("CourseInfo");
                _CourseInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseInfo");
                OnCourseInfoChanged();
            }
        }
        private global::System.String _CourseInfo;
        partial void OnCourseInfoChanging(global::System.String value);
        partial void OnCourseInfoChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        public static Department CreateDepartment(global::System.Int32 departmentID)
        {
            Department department = new Department();
            department.DepartmentID = departmentID;
            return department;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                if (_DepartmentID != value)
                {
                    OnDepartmentIDChanging(value);
                    ReportPropertyChanging("DepartmentID");
                    _DepartmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentID");
                    OnDepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DivisionID
        {
            get
            {
                return _DivisionID;
            }
            set
            {
                OnDivisionIDChanging(value);
                ReportPropertyChanging("DivisionID");
                _DivisionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivisionID");
                OnDivisionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DivisionID;
        partial void OnDivisionIDChanging(Nullable<global::System.Int32> value);
        partial void OnDivisionIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProgramChairSID
        {
            get
            {
                return _ProgramChairSID;
            }
            set
            {
                OnProgramChairSIDChanging(value);
                ReportPropertyChanging("ProgramChairSID");
                _ProgramChairSID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProgramChairSID");
                OnProgramChairSIDChanged();
            }
        }
        private global::System.String _ProgramChairSID;
        partial void OnProgramChairSIDChanging(global::System.String value);
        partial void OnProgramChairSIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassSchedule.Models", "FK_Departments_Division", "Division")]
        public Division Division
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Division>("ClassSchedule.Models.FK_Departments_Division", "Division").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Division>("ClassSchedule.Models.FK_Departments_Division", "Division").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Division> DivisionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Division>("ClassSchedule.Models.FK_Departments_Division", "Division");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Division>("ClassSchedule.Models.FK_Departments_Division", "Division", value);
                }
            }
        }

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassSchedule.Models", "FK_Subjects_Departments", "Subject")]
        public EntityCollection<Subject> Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Subject>("ClassSchedule.Models.FK_Subjects_Departments", "Subject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Subject>("ClassSchedule.Models.FK_Subjects_Departments", "Subject", value);
                }
            }
        }

        #endregion
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="Division")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Division : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Division object.
        /// </summary>
        /// <param name="divisionID">Initial value of the DivisionID property.</param>
        public static Division CreateDivision(global::System.Int32 divisionID)
        {
            Division division = new Division();
            division.DivisionID = divisionID;
            return division;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DivisionID
        {
            get
            {
                return _DivisionID;
            }
            set
            {
                if (_DivisionID != value)
                {
                    OnDivisionIDChanging(value);
                    ReportPropertyChanging("DivisionID");
                    _DivisionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DivisionID");
                    OnDivisionIDChanged();
                }
            }
        }
        private global::System.Int32 _DivisionID;
        partial void OnDivisionIDChanging(global::System.Int32 value);
        partial void OnDivisionIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassSchedule.Models", "FK_Departments_Division", "Department")]
        public EntityCollection<Department> Departments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Department>("ClassSchedule.Models.FK_Departments_Division", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Department>("ClassSchedule.Models.FK_Departments_Division", "Department", value);
                }
            }
        }

        #endregion
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="SectionCourseCrosslisting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SectionCourseCrosslisting : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new SectionCourseCrosslisting object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        public static SectionCourseCrosslisting CreateSectionCourseCrosslisting(global::System.String classID, global::System.String courseID)
        {
            SectionCourseCrosslisting sectionCourseCrosslisting = new SectionCourseCrosslisting();
            sectionCourseCrosslisting.ClassID = classID;
            sectionCourseCrosslisting.CourseID = courseID;
            return sectionCourseCrosslisting;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="SectionSeat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SectionSeat : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new SectionSeat object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static SectionSeat CreateSectionSeat(global::System.String classID)
        {
            SectionSeat sectionSeat = new SectionSeat();
            sectionSeat.ClassID = classID;
            return sectionSeat;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeatsAvailable
        {
            get
            {
                return _SeatsAvailable;
            }
            set
            {
                OnSeatsAvailableChanging(value);
                ReportPropertyChanging("SeatsAvailable");
                _SeatsAvailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatsAvailable");
                OnSeatsAvailableChanged();
            }
        }
        private Nullable<global::System.Int32> _SeatsAvailable;
        partial void OnSeatsAvailableChanging(Nullable<global::System.Int32> value);
        partial void OnSeatsAvailableChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="SectionsMeta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SectionsMeta : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new SectionsMeta object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static SectionsMeta CreateSectionsMeta(global::System.String classID)
        {
            SectionsMeta sectionsMeta = new SectionsMeta();
            sectionsMeta.ClassID = classID;
            return sectionsMeta;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Footnote
        {
            get
            {
                return _Footnote;
            }
            set
            {
                OnFootnoteChanging(value);
                ReportPropertyChanging("Footnote");
                _Footnote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Footnote");
                OnFootnoteChanged();
            }
        }
        private global::System.String _Footnote;
        partial void OnFootnoteChanging(global::System.String value);
        partial void OnFootnoteChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="Subject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subject : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new Subject object.
        /// </summary>
        /// <param name="subjectID">Initial value of the SubjectID property.</param>
        /// <param name="slug">Initial value of the Slug property.</param>
        public static Subject CreateSubject(global::System.Int32 subjectID, global::System.String slug)
        {
            Subject subject = new Subject();
            subject.SubjectID = subjectID;
            subject.Slug = slug;
            return subject;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubjectID
        {
            get
            {
                return _SubjectID;
            }
            set
            {
                if (_SubjectID != value)
                {
                    OnSubjectIDChanging(value);
                    ReportPropertyChanging("SubjectID");
                    _SubjectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubjectID");
                    OnSubjectIDChanged();
                }
            }
        }
        private global::System.Int32 _SubjectID;
        partial void OnSubjectIDChanging(global::System.Int32 value);
        partial void OnSubjectIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                OnDepartmentIDChanging(value);
                ReportPropertyChanging("DepartmentID");
                _DepartmentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentID");
                OnDepartmentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentID;
        partial void OnDepartmentIDChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Intro
        {
            get
            {
                return _Intro;
            }
            set
            {
                OnIntroChanging(value);
                ReportPropertyChanging("Intro");
                _Intro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Intro");
                OnIntroChanged();
            }
        }
        private global::System.String _Intro;
        partial void OnIntroChanging(global::System.String value);
        partial void OnIntroChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Slug
        {
            get
            {
                return _Slug;
            }
            set
            {
                OnSlugChanging(value);
                ReportPropertyChanging("Slug");
                _Slug = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Slug");
                OnSlugChanged();
            }
        }
        private global::System.String _Slug;
        partial void OnSlugChanging(global::System.String value);
        partial void OnSlugChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassSchedule.Models", "FK_Subjects_Departments", "Department")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ClassSchedule.Models.FK_Subjects_Departments", "Department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ClassSchedule.Models.FK_Subjects_Departments", "Department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ClassSchedule.Models.FK_Subjects_Departments", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("ClassSchedule.Models.FK_Subjects_Departments", "Department", value);
                }
            }
        }

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassSchedule.Models", "FK_SubjectsCoursePrefixes_Subjects", "SubjectsCoursePrefix")]
        public EntityCollection<SubjectsCoursePrefix> SubjectsCoursePrefixes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubjectsCoursePrefix>("ClassSchedule.Models.FK_SubjectsCoursePrefixes_Subjects", "SubjectsCoursePrefix");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubjectsCoursePrefix>("ClassSchedule.Models.FK_SubjectsCoursePrefixes_Subjects", "SubjectsCoursePrefix", value);
                }
            }
        }

        #endregion
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="SubjectsCoursePrefix")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubjectsCoursePrefix : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new SubjectsCoursePrefix object.
        /// </summary>
        /// <param name="subjectID">Initial value of the SubjectID property.</param>
        /// <param name="coursePrefixID">Initial value of the CoursePrefixID property.</param>
        public static SubjectsCoursePrefix CreateSubjectsCoursePrefix(global::System.Int32 subjectID, global::System.String coursePrefixID)
        {
            SubjectsCoursePrefix subjectsCoursePrefix = new SubjectsCoursePrefix();
            subjectsCoursePrefix.SubjectID = subjectID;
            subjectsCoursePrefix.CoursePrefixID = coursePrefixID;
            return subjectsCoursePrefix;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubjectID
        {
            get
            {
                return _SubjectID;
            }
            set
            {
                if (_SubjectID != value)
                {
                    OnSubjectIDChanging(value);
                    ReportPropertyChanging("SubjectID");
                    _SubjectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubjectID");
                    OnSubjectIDChanged();
                }
            }
        }
        private global::System.Int32 _SubjectID;
        partial void OnSubjectIDChanging(global::System.Int32 value);
        partial void OnSubjectIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CoursePrefixID
        {
            get
            {
                return _CoursePrefixID;
            }
            set
            {
                if (_CoursePrefixID != value)
                {
                    OnCoursePrefixIDChanging(value);
                    ReportPropertyChanging("CoursePrefixID");
                    _CoursePrefixID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CoursePrefixID");
                    OnCoursePrefixIDChanged();
                }
            }
        }
        private global::System.String _CoursePrefixID;
        partial void OnCoursePrefixIDChanging(global::System.String value);
        partial void OnCoursePrefixIDChanged();

        #endregion

        #region Navigation Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClassSchedule.Models", "FK_SubjectsCoursePrefixes_Subjects", "Subject")]
        public Subject Subject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subject>("ClassSchedule.Models.FK_SubjectsCoursePrefixes_Subjects", "Subject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subject>("ClassSchedule.Models.FK_SubjectsCoursePrefixes_Subjects", "Subject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Subject> SubjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Subject>("ClassSchedule.Models.FK_SubjectsCoursePrefixes_Subjects", "Subject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Subject>("ClassSchedule.Models.FK_SubjectsCoursePrefixes_Subjects", "Subject", value);
                }
            }
        }

        #endregion
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="vw_Class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_Class : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_Class object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static vw_Class Createvw_Class(global::System.String classID)
        {
            vw_Class vw_Class = new vw_Class();
            vw_Class.ClassID = classID;
            return vw_Class;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YearQuarterID
        {
            get
            {
                return _YearQuarterID;
            }
            set
            {
                OnYearQuarterIDChanging(value);
                ReportPropertyChanging("YearQuarterID");
                _YearQuarterID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YearQuarterID");
                OnYearQuarterIDChanged();
            }
        }
        private global::System.String _YearQuarterID;
        partial void OnYearQuarterIDChanging(global::System.String value);
        partial void OnYearQuarterIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemNumber
        {
            get
            {
                return _ItemNumber;
            }
            set
            {
                OnItemNumberChanging(value);
                ReportPropertyChanging("ItemNumber");
                _ItemNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemNumber");
                OnItemNumberChanged();
            }
        }
        private global::System.String _ItemNumber;
        partial void OnItemNumberChanging(global::System.String value);
        partial void OnItemNumberChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseNumber
        {
            get
            {
                return _CourseNumber;
            }
            set
            {
                OnCourseNumberChanging(value);
                ReportPropertyChanging("CourseNumber");
                _CourseNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseNumber");
                OnCourseNumberChanged();
            }
        }
        private global::System.String _CourseNumber;
        partial void OnCourseNumberChanging(global::System.String value);
        partial void OnCourseNumberChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClassCapacity
        {
            get
            {
                return _ClassCapacity;
            }
            set
            {
                OnClassCapacityChanging(value);
                ReportPropertyChanging("ClassCapacity");
                _ClassCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassCapacity");
                OnClassCapacityChanged();
            }
        }
        private Nullable<global::System.Int32> _ClassCapacity;
        partial void OnClassCapacityChanging(Nullable<global::System.Int32> value);
        partial void OnClassCapacityChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentsEnrolled
        {
            get
            {
                return _StudentsEnrolled;
            }
            set
            {
                OnStudentsEnrolledChanging(value);
                ReportPropertyChanging("StudentsEnrolled");
                _StudentsEnrolled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentsEnrolled");
                OnStudentsEnrolledChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentsEnrolled;
        partial void OnStudentsEnrolledChanging(Nullable<global::System.Int32> value);
        partial void OnStudentsEnrolledChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    #endregion

}
