//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CTCClassSchedule.Models
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [DebuggerDisplay("ClassID = {ClassID}")]
    public partial class ClassScheduleDataEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new ClassScheduleDataEntities object using the connection string found in the 'ClassScheduleDataEntities' section of the application configuration file.
        /// </summary>
        public ClassScheduleDataEntities() : base("name=ClassScheduleDataEntities", "ClassScheduleDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ClassScheduleDataEntities object.
        /// </summary>
        public ClassScheduleDataEntities(string connectionString) : base(connectionString, "ClassScheduleDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ClassScheduleDataEntities object.
        /// </summary>
        public ClassScheduleDataEntities(EntityConnection connection) : base(connection, "ClassScheduleDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_ClassScheduleData> vw_ClassScheduleData
        {
            get
            {
                if ((_vw_ClassScheduleData == null))
                {
                    _vw_ClassScheduleData = base.CreateObjectSet<vw_ClassScheduleData>("vw_ClassScheduleData");
                }
                return _vw_ClassScheduleData;
            }
        }
        private ObjectSet<vw_ClassScheduleData> _vw_ClassScheduleData;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_ClassScheduleData EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_ClassScheduleData(vw_ClassScheduleData vw_ClassScheduleData)
        {
            base.AddObject("vw_ClassScheduleData", vw_ClassScheduleData);
        }

        #endregion
    }


    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassScheduleDataModel", Name="vw_ClassScheduleData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_ClassScheduleData : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_ClassScheduleData object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static vw_ClassScheduleData Createvw_ClassScheduleData(global::System.String classID)
        {
            vw_ClassScheduleData vw_ClassScheduleData = new vw_ClassScheduleData();
            vw_ClassScheduleData.ClassID = classID;
            return vw_ClassScheduleData;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YearQuarterID
        {
            get
            {
                return _YearQuarterID;
            }
            set
            {
                OnYearQuarterIDChanging(value);
                ReportPropertyChanging("YearQuarterID");
                _YearQuarterID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YearQuarterID");
                OnYearQuarterIDChanged();
            }
        }
        private global::System.String _YearQuarterID;
        partial void OnYearQuarterIDChanging(global::System.String value);
        partial void OnYearQuarterIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeatsAvailable
        {
            get
            {
                return _SeatsAvailable;
            }
            set
            {
                OnSeatsAvailableChanging(value);
                ReportPropertyChanging("SeatsAvailable");
                _SeatsAvailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatsAvailable");
                OnSeatsAvailableChanged();
            }
        }
        private Nullable<global::System.Int32> _SeatsAvailable;
        partial void OnSeatsAvailableChanging(Nullable<global::System.Int32> value);
        partial void OnSeatsAvailableChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseFootnote
        {
            get
            {
                return _CourseFootnote;
            }
            set
            {
                OnCourseFootnoteChanging(value);
                ReportPropertyChanging("CourseFootnote");
                _CourseFootnote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseFootnote");
                OnCourseFootnoteChanged();
            }
        }
        private global::System.String _CourseFootnote;
        partial void OnCourseFootnoteChanging(global::System.String value);
        partial void OnCourseFootnoteChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SectionFootnote
        {
            get
            {
                return _SectionFootnote;
            }
            set
            {
                OnSectionFootnoteChanging(value);
                ReportPropertyChanging("SectionFootnote");
                _SectionFootnote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SectionFootnote");
                OnSectionFootnoteChanged();
            }
        }
        private global::System.String _SectionFootnote;
        partial void OnSectionFootnoteChanging(global::System.String value);
        partial void OnSectionFootnoteChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Abbreviation
        {
            get
            {
                return _Abbreviation;
            }
            set
            {
                OnAbbreviationChanging(value);
                ReportPropertyChanging("Abbreviation");
                _Abbreviation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Abbreviation");
                OnAbbreviationChanged();
            }
        }
        private global::System.String _Abbreviation;
        partial void OnAbbreviationChanging(global::System.String value);
        partial void OnAbbreviationChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProgramURL
        {
            get
            {
                return _ProgramURL;
            }
            set
            {
                OnProgramURLChanging(value);
                ReportPropertyChanging("ProgramURL");
                _ProgramURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProgramURL");
                OnProgramURLChanged();
            }
        }
        private global::System.String _ProgramURL;
        partial void OnProgramURLChanging(global::System.String value);
        partial void OnProgramURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.String _Division;
        partial void OnDivisionChanging(global::System.String value);
        partial void OnDivisionChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactPhone
        {
            get
            {
                return _ContactPhone;
            }
            set
            {
                OnContactPhoneChanging(value);
                ReportPropertyChanging("ContactPhone");
                _ContactPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactPhone");
                OnContactPhoneChanged();
            }
        }
        private global::System.String _ContactPhone;
        partial void OnContactPhoneChanging(global::System.String value);
        partial void OnContactPhoneChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Intro
        {
            get
            {
                return _Intro;
            }
            set
            {
                OnIntroChanging(value);
                ReportPropertyChanging("Intro");
                _Intro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Intro");
                OnIntroChanged();
            }
        }
        private global::System.String _Intro;
        partial void OnIntroChanging(global::System.String value);
        partial void OnIntroChanged();

        #endregion

    }

    #endregion

}
