//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CTCClassSchedule.Models
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClassScheduleDb : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new ClassScheduleDb object using the connection string found in the 'ClassScheduleDb' section of the application configuration file.
        /// </summary>
        public ClassScheduleDb() : base("name=ClassScheduleDb", "ClassScheduleDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ClassScheduleDb object.
        /// </summary>
        public ClassScheduleDb(string connectionString) : base(connectionString, "ClassScheduleDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new ClassScheduleDb object.
        /// </summary>
        public ClassScheduleDb(EntityConnection connection) : base(connection, "ClassScheduleDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_ClassScheduleData> vw_ClassScheduleData
        {
            get
            {
                if ((_vw_ClassScheduleData == null))
                {
                    _vw_ClassScheduleData = base.CreateObjectSet<vw_ClassScheduleData>("vw_ClassScheduleData");
                }
                return _vw_ClassScheduleData;
            }
        }
        private ObjectSet<vw_ClassScheduleData> _vw_ClassScheduleData;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_ClassSearch> vw_ClassSearch
        {
            get
            {
                if ((_vw_ClassSearch == null))
                {
                    _vw_ClassSearch = base.CreateObjectSet<vw_ClassSearch>("vw_ClassSearch");
                }
                return _vw_ClassSearch;
            }
        }
        private ObjectSet<vw_ClassSearch> _vw_ClassSearch;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_CourseSearch> vw_CourseSearch
        {
            get
            {
                if ((_vw_CourseSearch == null))
                {
                    _vw_CourseSearch = base.CreateObjectSet<vw_CourseSearch>("vw_CourseSearch");
                }
                return _vw_CourseSearch;
            }
        }
        private ObjectSet<vw_CourseSearch> _vw_CourseSearch;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_ProgramInformation> vw_ProgramInformation
        {
            get
            {
                if ((_vw_ProgramInformation == null))
                {
                    _vw_ProgramInformation = base.CreateObjectSet<vw_ProgramInformation>("vw_ProgramInformation");
                }
                return _vw_ProgramInformation;
            }
        }
        private ObjectSet<vw_ProgramInformation> _vw_ProgramInformation;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_SeatAvailability> vw_SeatAvailability
        {
            get
            {
                if ((_vw_SeatAvailability == null))
                {
                    _vw_SeatAvailability = base.CreateObjectSet<vw_SeatAvailability>("vw_SeatAvailability");
                }
                return _vw_SeatAvailability;
            }
        }
        private ObjectSet<vw_SeatAvailability> _vw_SeatAvailability;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeatAvailability> SeatAvailabilities
        {
            get
            {
                if ((_SeatAvailabilities == null))
                {
                    _SeatAvailabilities = base.CreateObjectSet<SeatAvailability>("SeatAvailabilities");
                }
                return _SeatAvailabilities;
            }
        }
        private ObjectSet<SeatAvailability> _SeatAvailabilities;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_ClassScheduleData EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_ClassScheduleData(vw_ClassScheduleData vw_ClassScheduleData)
        {
            base.AddObject("vw_ClassScheduleData", vw_ClassScheduleData);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_ClassSearch EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_ClassSearch(vw_ClassSearch vw_ClassSearch)
        {
            base.AddObject("vw_ClassSearch", vw_ClassSearch);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_CourseSearch EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_CourseSearch(vw_CourseSearch vw_CourseSearch)
        {
            base.AddObject("vw_CourseSearch", vw_CourseSearch);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_ProgramInformation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_ProgramInformation(vw_ProgramInformation vw_ProgramInformation)
        {
            base.AddObject("vw_ProgramInformation", vw_ProgramInformation);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the vw_SeatAvailability EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_SeatAvailability(vw_SeatAvailability vw_SeatAvailability)
        {
            base.AddObject("vw_SeatAvailability", vw_SeatAvailability);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the SeatAvailabilities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeatAvailabilities(SeatAvailability seatAvailability)
        {
            base.AddObject("SeatAvailabilities", seatAvailability);
        }

        #endregion
    }


    #endregion

    #region Entities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="SeatAvailability")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeatAvailability : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new SeatAvailability object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static SeatAvailability CreateSeatAvailability(global::System.String classID)
        {
            SeatAvailability seatAvailability = new SeatAvailability();
            seatAvailability.ClassID = classID;
            return seatAvailability;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeatsAvailable
        {
            get
            {
                return _SeatsAvailable;
            }
            set
            {
                OnSeatsAvailableChanging(value);
                ReportPropertyChanging("SeatsAvailable");
                _SeatsAvailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatsAvailable");
                OnSeatsAvailableChanged();
            }
        }
        private Nullable<global::System.Int32> _SeatsAvailable;
        partial void OnSeatsAvailableChanging(Nullable<global::System.Int32> value);
        partial void OnSeatsAvailableChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="vw_ClassScheduleData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_ClassScheduleData : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_ClassScheduleData object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static vw_ClassScheduleData Createvw_ClassScheduleData(global::System.String classID)
        {
            vw_ClassScheduleData vw_ClassScheduleData = new vw_ClassScheduleData();
            vw_ClassScheduleData.ClassID = classID;
            return vw_ClassScheduleData;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YearQuarterID
        {
            get
            {
                return _YearQuarterID;
            }
            set
            {
                OnYearQuarterIDChanging(value);
                ReportPropertyChanging("YearQuarterID");
                _YearQuarterID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YearQuarterID");
                OnYearQuarterIDChanged();
            }
        }
        private global::System.String _YearQuarterID;
        partial void OnYearQuarterIDChanging(global::System.String value);
        partial void OnYearQuarterIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeatsAvailable
        {
            get
            {
                return _SeatsAvailable;
            }
            set
            {
                OnSeatsAvailableChanging(value);
                ReportPropertyChanging("SeatsAvailable");
                _SeatsAvailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatsAvailable");
                OnSeatsAvailableChanged();
            }
        }
        private Nullable<global::System.Int32> _SeatsAvailable;
        partial void OnSeatsAvailableChanging(Nullable<global::System.Int32> value);
        partial void OnSeatsAvailableChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseFootnote
        {
            get
            {
                return _CourseFootnote;
            }
            set
            {
                OnCourseFootnoteChanging(value);
                ReportPropertyChanging("CourseFootnote");
                _CourseFootnote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseFootnote");
                OnCourseFootnoteChanged();
            }
        }
        private global::System.String _CourseFootnote;
        partial void OnCourseFootnoteChanging(global::System.String value);
        partial void OnCourseFootnoteChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SectionFootnote
        {
            get
            {
                return _SectionFootnote;
            }
            set
            {
                OnSectionFootnoteChanging(value);
                ReportPropertyChanging("SectionFootnote");
                _SectionFootnote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SectionFootnote");
                OnSectionFootnoteChanged();
            }
        }
        private global::System.String _SectionFootnote;
        partial void OnSectionFootnoteChanging(global::System.String value);
        partial void OnSectionFootnoteChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Abbreviation
        {
            get
            {
                return _Abbreviation;
            }
            set
            {
                OnAbbreviationChanging(value);
                ReportPropertyChanging("Abbreviation");
                _Abbreviation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Abbreviation");
                OnAbbreviationChanged();
            }
        }
        private global::System.String _Abbreviation;
        partial void OnAbbreviationChanging(global::System.String value);
        partial void OnAbbreviationChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProgramURL
        {
            get
            {
                return _ProgramURL;
            }
            set
            {
                OnProgramURLChanging(value);
                ReportPropertyChanging("ProgramURL");
                _ProgramURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProgramURL");
                OnProgramURLChanged();
            }
        }
        private global::System.String _ProgramURL;
        partial void OnProgramURLChanging(global::System.String value);
        partial void OnProgramURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.String _Division;
        partial void OnDivisionChanging(global::System.String value);
        partial void OnDivisionChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactPhone
        {
            get
            {
                return _ContactPhone;
            }
            set
            {
                OnContactPhoneChanging(value);
                ReportPropertyChanging("ContactPhone");
                _ContactPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactPhone");
                OnContactPhoneChanged();
            }
        }
        private global::System.String _ContactPhone;
        partial void OnContactPhoneChanging(global::System.String value);
        partial void OnContactPhoneChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Intro
        {
            get
            {
                return _Intro;
            }
            set
            {
                OnIntroChanging(value);
                ReportPropertyChanging("Intro");
                _Intro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Intro");
                OnIntroChanged();
            }
        }
        private global::System.String _Intro;
        partial void OnIntroChanging(global::System.String value);
        partial void OnIntroChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="vw_ClassSearch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_ClassSearch : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_ClassSearch object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static vw_ClassSearch Createvw_ClassSearch(global::System.String classID)
        {
            vw_ClassSearch vw_ClassSearch = new vw_ClassSearch();
            vw_ClassSearch.ClassID = classID;
            return vw_ClassSearch;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YearQuarterID
        {
            get
            {
                return _YearQuarterID;
            }
            set
            {
                OnYearQuarterIDChanging(value);
                ReportPropertyChanging("YearQuarterID");
                _YearQuarterID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YearQuarterID");
                OnYearQuarterIDChanged();
            }
        }
        private global::System.String _YearQuarterID;
        partial void OnYearQuarterIDChanging(global::System.String value);
        partial void OnYearQuarterIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemNumber
        {
            get
            {
                return _ItemNumber;
            }
            set
            {
                OnItemNumberChanging(value);
                ReportPropertyChanging("ItemNumber");
                _ItemNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemNumber");
                OnItemNumberChanged();
            }
        }
        private global::System.String _ItemNumber;
        partial void OnItemNumberChanging(global::System.String value);
        partial void OnItemNumberChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseTitle
        {
            get
            {
                return _CourseTitle;
            }
            set
            {
                OnCourseTitleChanging(value);
                ReportPropertyChanging("CourseTitle");
                _CourseTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseTitle");
                OnCourseTitleChanged();
            }
        }
        private global::System.String _CourseTitle;
        partial void OnCourseTitleChanging(global::System.String value);
        partial void OnCourseTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseSubject
        {
            get
            {
                return _CourseSubject;
            }
            set
            {
                OnCourseSubjectChanging(value);
                ReportPropertyChanging("CourseSubject");
                _CourseSubject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseSubject");
                OnCourseSubjectChanged();
            }
        }
        private global::System.String _CourseSubject;
        partial void OnCourseSubjectChanging(global::System.String value);
        partial void OnCourseSubjectChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Footnotes
        {
            get
            {
                return _Footnotes;
            }
            set
            {
                OnFootnotesChanging(value);
                ReportPropertyChanging("Footnotes");
                _Footnotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Footnotes");
                OnFootnotesChanged();
            }
        }
        private global::System.String _Footnotes;
        partial void OnFootnotesChanging(global::System.String value);
        partial void OnFootnotesChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InstructorName
        {
            get
            {
                return _InstructorName;
            }
            set
            {
                OnInstructorNameChanging(value);
                ReportPropertyChanging("InstructorName");
                _InstructorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InstructorName");
                OnInstructorNameChanged();
            }
        }
        private global::System.String _InstructorName;
        partial void OnInstructorNameChanging(global::System.String value);
        partial void OnInstructorNameChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseDescription
        {
            get
            {
                return _CourseDescription;
            }
            set
            {
                OnCourseDescriptionChanging(value);
                ReportPropertyChanging("CourseDescription");
                _CourseDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseDescription");
                OnCourseDescriptionChanged();
            }
        }
        private global::System.String _CourseDescription;
        partial void OnCourseDescriptionChanging(global::System.String value);
        partial void OnCourseDescriptionChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseDescription2
        {
            get
            {
                return _CourseDescription2;
            }
            set
            {
                OnCourseDescription2Changing(value);
                ReportPropertyChanging("CourseDescription2");
                _CourseDescription2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseDescription2");
                OnCourseDescription2Changed();
            }
        }
        private global::System.String _CourseDescription2;
        partial void OnCourseDescription2Changing(global::System.String value);
        partial void OnCourseDescription2Changed();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="vw_CourseSearch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_CourseSearch : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_CourseSearch object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        public static vw_CourseSearch Createvw_CourseSearch(global::System.String courseID)
        {
            vw_CourseSearch vw_CourseSearch = new vw_CourseSearch();
            vw_CourseSearch.CourseID = courseID;
            return vw_CourseSearch;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String YearQuarterID
        {
            get
            {
                return _YearQuarterID;
            }
            set
            {
                OnYearQuarterIDChanging(value);
                ReportPropertyChanging("YearQuarterID");
                _YearQuarterID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("YearQuarterID");
                OnYearQuarterIDChanged();
            }
        }
        private global::System.String _YearQuarterID;
        partial void OnYearQuarterIDChanging(global::System.String value);
        partial void OnYearQuarterIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseTitle
        {
            get
            {
                return _CourseTitle;
            }
            set
            {
                OnCourseTitleChanging(value);
                ReportPropertyChanging("CourseTitle");
                _CourseTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseTitle");
                OnCourseTitleChanged();
            }
        }
        private global::System.String _CourseTitle;
        partial void OnCourseTitleChanging(global::System.String value);
        partial void OnCourseTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseTitle2
        {
            get
            {
                return _CourseTitle2;
            }
            set
            {
                OnCourseTitle2Changing(value);
                ReportPropertyChanging("CourseTitle2");
                _CourseTitle2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseTitle2");
                OnCourseTitle2Changed();
            }
        }
        private global::System.String _CourseTitle2;
        partial void OnCourseTitle2Changing(global::System.String value);
        partial void OnCourseTitle2Changed();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Credits
        {
            get
            {
                return _Credits;
            }
            set
            {
                OnCreditsChanging(value);
                ReportPropertyChanging("Credits");
                _Credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Credits");
                OnCreditsChanged();
            }
        }
        private Nullable<global::System.Decimal> _Credits;
        partial void OnCreditsChanging(Nullable<global::System.Decimal> value);
        partial void OnCreditsChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseDescription
        {
            get
            {
                return _CourseDescription;
            }
            set
            {
                OnCourseDescriptionChanging(value);
                ReportPropertyChanging("CourseDescription");
                _CourseDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseDescription");
                OnCourseDescriptionChanged();
            }
        }
        private global::System.String _CourseDescription;
        partial void OnCourseDescriptionChanging(global::System.String value);
        partial void OnCourseDescriptionChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseDescription2
        {
            get
            {
                return _CourseDescription2;
            }
            set
            {
                OnCourseDescription2Changing(value);
                ReportPropertyChanging("CourseDescription2");
                _CourseDescription2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseDescription2");
                OnCourseDescription2Changed();
            }
        }
        private global::System.String _CourseDescription2;
        partial void OnCourseDescription2Changing(global::System.String value);
        partial void OnCourseDescription2Changed();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="vw_ProgramInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_ProgramInformation : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_ProgramInformation object.
        /// </summary>
        /// <param name="abbreviation">Initial value of the Abbreviation property.</param>
        public static vw_ProgramInformation Createvw_ProgramInformation(global::System.String abbreviation)
        {
            vw_ProgramInformation vw_ProgramInformation = new vw_ProgramInformation();
            vw_ProgramInformation.Abbreviation = abbreviation;
            return vw_ProgramInformation;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AbbreviationTrimmed
        {
            get
            {
                return _AbbreviationTrimmed;
            }
            set
            {
                OnAbbreviationTrimmedChanging(value);
                ReportPropertyChanging("AbbreviationTrimmed");
                _AbbreviationTrimmed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AbbreviationTrimmed");
                OnAbbreviationTrimmedChanged();
            }
        }
        private global::System.String _AbbreviationTrimmed;
        partial void OnAbbreviationTrimmedChanging(global::System.String value);
        partial void OnAbbreviationTrimmedChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Abbreviation
        {
            get
            {
                return _Abbreviation;
            }
            set
            {
                if (_Abbreviation != value)
                {
                    OnAbbreviationChanging(value);
                    ReportPropertyChanging("Abbreviation");
                    _Abbreviation = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Abbreviation");
                    OnAbbreviationChanged();
                }
            }
        }
        private global::System.String _Abbreviation;
        partial void OnAbbreviationChanging(global::System.String value);
        partial void OnAbbreviationChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProgramURL
        {
            get
            {
                return _ProgramURL;
            }
            set
            {
                OnProgramURLChanging(value);
                ReportPropertyChanging("ProgramURL");
                _ProgramURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProgramURL");
                OnProgramURLChanged();
            }
        }
        private global::System.String _ProgramURL;
        partial void OnProgramURLChanging(global::System.String value);
        partial void OnProgramURLChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.String _Division;
        partial void OnDivisionChanging(global::System.String value);
        partial void OnDivisionChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactPhone
        {
            get
            {
                return _ContactPhone;
            }
            set
            {
                OnContactPhoneChanging(value);
                ReportPropertyChanging("ContactPhone");
                _ContactPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactPhone");
                OnContactPhoneChanged();
            }
        }
        private global::System.String _ContactPhone;
        partial void OnContactPhoneChanging(global::System.String value);
        partial void OnContactPhoneChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Intro
        {
            get
            {
                return _Intro;
            }
            set
            {
                OnIntroChanging(value);
                ReportPropertyChanging("Intro");
                _Intro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Intro");
                OnIntroChanged();
            }
        }
        private global::System.String _Intro;
        partial void OnIntroChanging(global::System.String value);
        partial void OnIntroChanged();

        #endregion

    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClassSchedule.Models", Name="vw_SeatAvailability")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_SeatAvailability : EntityObject
    {
        #region Factory Method

        /// <summary>
        /// Create a new vw_SeatAvailability object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        public static vw_SeatAvailability Createvw_SeatAvailability(global::System.String classID)
        {
            vw_SeatAvailability vw_SeatAvailability = new vw_SeatAvailability();
            vw_SeatAvailability.ClassID = classID;
            return vw_SeatAvailability;
        }

        #endregion
        #region Primitive Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeatsAvailable
        {
            get
            {
                return _SeatsAvailable;
            }
            set
            {
                OnSeatsAvailableChanging(value);
                ReportPropertyChanging("SeatsAvailable");
                _SeatsAvailable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeatsAvailable");
                OnSeatsAvailableChanged();
            }
        }
        private Nullable<global::System.Int32> _SeatsAvailable;
        partial void OnSeatsAvailableChanging(Nullable<global::System.Int32> value);
        partial void OnSeatsAvailableChanged();

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();

        #endregion

    }

    #endregion

}
