IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CAMPUS\SSOUTHVM1-N216K$')
CREATE LOGIN [CAMPUS\SSOUTHVM1-N216K$] FROM WINDOWS
GO
CREATE USER [CAMPUS\SSOUTHVM1-N216K$] FOR LOGIN [CAMPUS\SSOUTHVM1-N216K$]
GO
