IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'CAMPUS\JUAN-VM-WIN7$')
CREATE LOGIN [CAMPUS\JUAN-VM-WIN7$] FROM WINDOWS
GO
CREATE USER [CAMPUS\JUAN-VM-WIN7$] FOR LOGIN [CAMPUS\JUAN-VM-WIN7$]
GO
